### PR TITLE
🗄️ Update environment variables

### PR DESCRIPTION
**Pull request by KTong821**
## Purpose
Patch a previous PR that made changes to the `.env` file. Added IS_DATABASE_LOCAL to README.md under server directory.

### CODE REVIEW

**Review by jeffzh4ng — DISMISSED** [review]
Great initiative :D

**Comment by ShreyasPrasad** [comment]
LGTM

**Comment by xujustinj** [comment]
I think @ShreyasPrasad said "LGTM" but didn't approve because he wants a new dev to give the approval. I'll do the same...

LGTM

😄

**Review by evtyz — DISMISSED** [review]
LGTM!

**Review by xujustinj — APPROVED** [review]

**Review by jeffzh4ng — APPROVED** [review]

**Pull request merged**
